name: Build and push Docker image upon release

on:
  # Build and push Docker images *only* for releases.
  release:
    types: [published] # , created, edited

jobs:
  push_to_registry:
    name: Build and push Docker image to Docker Hub
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Push to Docker Hub
        uses: VaultVulp/gp-docker-action@1.1.8 # Info: https://github.com/docker/build-push-action/tree/releases/v1#tags
        with:
          github-token: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
          image-name: docker-cicd-python
	  
